//
// Created by Rohit Bohra on 10/06/24.
//

#ifndef RUBIKSCUBESOLVER_GENERICRUBIKCUBE_H
#define RUBIKSCUBESOLVER_GENERICRUBIKCUBE_H


class GenericRubikCube {

};


#endif //RUBIKSCUBESOLVER_GENERICRUBIKCUBE_H
